### ISSUE TITLE
编译过程报错

### ISSUE THREAD

**Issue by JackSatellite** [liaojack8/AndroidKiller#1]
Exception in thread "main" b.a.a.e: resource spec: 0x01010540

**Comment by liaojack8** [comment]
0x01010540 means the SDK version is too high to compile.
Android Killer Default use ShakaApktool.jar which be named "Android Killer Default APKTOOL", please select apktool_2.4.1 to compile your project.
![image](https://user-images.githubusercontent.com/23449425/93169755-5dbbe880-f758-11ea-957c-2392084c3dec.png)
