### ISSUE TITLE
编译之后应该进行4位对齐，否则安装会报错

### ISSUE THREAD

**Issue by hexi** [liaojack8/AndroidKiller#2]
adb: failed to install app-release_killer.apk: Failure [-124: Failed parse during installPackageLI: com.xx.xx.xxx: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]

**Comment by liaojack8** [comment]
手動解決吧, 這工具是方便入門使用, 對比現在新的Android系統, 已經過時了, 換個工具或是直接手動對齊並且重簽名
